overrides:
  '@typescript-eslint/utils': ^8.56.1
  esbuild: ^0.27.3
  typescript-eslint: ^8.56.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - rolldown
  - unrs-resolver
