packages:
  - .

catalog:
  '@iconify-json/fa-brands': ^1.2.1
  '@iconify-json/fluent-emoji-flat': ^1.2.3
  '@iconify-json/radix-icons': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/vscode-icons': ^1.2.20
  '@ntnyq/eslint-config': ^4.2.0
  '@ntnyq/prettier-config': ^2.0.0
  '@nuxt-dev/medium-zoom': ^0.1.0
  '@nuxt/content': ^3.5.1
  '@nuxt/eslint': ^1.3.1
  '@types/prompts': ^2.4.9
  '@unocss/nuxt': ^66.1.1
  '@unocss/reset': ^66.1.1
  '@vercel/analytics': ^1.5.0
  '@vite-pwa/nuxt': ^1.0.0
  '@vueuse/nuxt': ^13.1.0
  bumpp: ^10.1.0
  consola: ^3.4.2
  eslint: ^9.26.0
  floating-vue: ^5.2.2
  husky: ^9.1.7
  medium-zoom: ^1.1.0
  motion-v: ^1.0.2
  nano-staged: ^0.8.0
  npm-run-all2: ^8.0.1
  nuxt: ^3.17.2
  prettier: ^3.5.3
  prompts: ^2.4.2
  tsx: ^4.19.4
  typescript: ^5.8.3
  unocss: ^66.1.1
  vite: npm:rolldown-vite@latest
  vue-tsc: ^2.2.10
  workbox-build: ^7.3.0

overrides:
  '@vueuse/core': ^13.1.0
  '@vueuse/shared': ^13.1.0
  esbuild: ^0.25.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - rolldown
