packages:
  - .

overrides:
  '@vueuse/core': ^13.4.0
  '@vueuse/shared': ^13.4.0
  esbuild: ^0.25.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - rolldown
  - unrs-resolver
