packages:
  - .

overrides:
  '@vueuse/core': ^13.2.0
  '@vueuse/shared': ^13.2.0
  esbuild: ^0.25.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - rolldown
  - unrs-resolver
