overrides:
  '@typescript-eslint/utils': ^8.57.2
  esbuild: ^0.27.4
  typescript-eslint: ^8.57.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - rolldown
  - unrs-resolver
