// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFeatherTwitter: typeof import('~icons/feather/twitter')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    IUilGithubAlt: typeof import('~icons/uil/github-alt')['default']
    Nana: typeof import('./components/Nana.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
